### PR TITLE
Added CocoaPods support

### PR DESCRIPTION
**Pull request by ashfurrow**
Hey there! Really nifty project! I thought I'd add CocoaPods support so it could be used by more developers. Let me now if I can help at all.

### CODE REVIEW

**Comment by lilyball** [comment]
Thanks! I don't personally use CocoaPods, but it looks pretty straightforward. The iOS deployment target can actually be bumped to 7.0 if you want, it's only 8.0 right now because dynamic frameworks require iOS 8, but CocoaPods doesn't (necessarily) use dynamic frameworks. I'll just merge it as-is though, because I don't want to bother testing ;)

**Comment by ashfurrow** [comment]
Cool cool – are you comfortable pushing the podspec to CocoaPods? Or would you like me to manage that?

**Comment by lilyball** [comment]
I can do that. I'm just updating CocoaPods right now to push it.

**Comment by lilyball** [comment]
It's been pushed. Looks like their search indexes don't update live, and for some reason https://cocoapods.org/pods/swift-tsao now just redirects to the GitHub page instead of showing the pod info, but I guess it works.

**Comment by ashfurrow** [comment]
Aye, generating the docs and metadata about the pod takes time (don't know how long – @orta?) so it redirects until it's done.

**Comment by orta** [comment]
usually an hour or two, swift libraries have to be fully compiled for all platforms etc etc so it gets queued up - looks like docs are already up, so probably not too long, http://cocoadocs.org/docsets/swift-tsao/2.0/Structs/AssocMap.html

**Pull request merged**
